apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: httpbin
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: httpbin
spec:
  gateways:
  - mesh
  hosts:
  - httpbin.org
  tls:
  - match:
    - port: 443
      sniHosts:
      - httpbin.org
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
      weight: 100