---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-grpc
spec:
  hosts:
    - server-grpc.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - route:
        - destination:
            host: grpc
            port:
              number: 9000