apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: client-grpc
    version: {{ .Values.client.version }}
    app.kubernetes.io/name: client-grpc
    app.kubernetes.io/version: {{ .Values.client.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: client-grpc
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: client-grpc
    weight: 100