apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: order
    version: {{ .Values.order.version }}
    app.kubernetes.io/name: order
    app.kubernetes.io/version: {{ .Values.order.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: order
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: order
    weight: 100