apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: product
    version: {{ .Values.product.version }}
    app.kubernetes.io/name: product
    app.kubernetes.io/version: {{ .Values.product.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: product
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: product
    weight: 100