apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: client-{{ .Values.client.version }},server-{{ .Values.server.version }}
    app.openshift.io/vcs-ref: {{ .Values.server.version }}
  labels:
    app: server-grpc
    version: {{ .Values.server.version }}
    app.kubernetes.io/name: server-grpc
    app.kubernetes.io/version: {{ .Values.server.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    app.openshift.io/runtime: quarkus
    group: {{ .Values.appName }}
  name: server-grpc-{{ .Values.server.version }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: server-grpc
      version: {{ .Values.server.version }}
  template:
    metadata:
      labels:
        app: server-grpc
        version: {{ .Values.server.version }}
    spec:
      containers:
      - image: {{ .Values.server.image }}:{{ .Values.server.version }}
        imagePullPolicy: Always
        name: grpc
        ports:
        - containerPort: 9000
          protocol: grcp
        volumeMounts:
          - name: quarkus-config-volume
            mountPath: /deployments/config
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}Mi
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}Mi
      volumes:
        - name: quarkus-config-volume
          configMap:
            name: grpcconfig
            defaultMode: 420  