apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
    version: {{ .Values.user.version }}
    app.kubernetes.io/name: user
    app.kubernetes.io/version: {{ .Values.user.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: user
spec:
  ports:
  - name: grpc
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user
    version: {{ .Values.user.version }}