apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: user
    version: {{ .Values.user.version }}
    app.kubernetes.io/name: user
    app.kubernetes.io/version: {{ .Values.user.version }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ .Values.appName }}
    group: {{ .Values.appName }}
  name: user
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: user
    weight: 100